{
 "title": "Monitoreo VPS",
 "description": "Monitoreo completo sobre la VPS",
 "tags": [ "VPS" ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(node_cpu_seconds_total,instance)"
    }
   },
   { "name": "job", "label": "Job", "query": { "query": "label_values(up,job)" } },
   {
    "name": "container",
    "label": "Container",
    "query": {
     "query": "label_values(container_cpu_usage_seconds_total,name)"
    }
   },
   {
    "name": "datname",
    "label": "DatName",
    "query": {
     "query": "label_values(pg_stat_activity_count,datname)"
    }
   },
   {
    "name": "mountpoint",
    "label": "MountPoint",
    "query": {
     "query": "label_values(node_filesystem_size_bytes,mountpoint)"
    }
   },
   {
    "name": "device",
    "label": "Device",
    "query": {
     "query": "label_values(node_network_receive_bytes_total,device)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "OVERVIEW",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Used",
     "type": "gauge",
     "description": "Porcentaje del uso del CPU",
     "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "100 - (avg by (instance)(rate(node_cpu_seconds_total{mode=\"idle\", instance=\"$instance\", job=\"$job\"}[1m])) * 100)"
      }
     ]
    },
    {
     "title": "RAM Used",
     "type": "gauge",
     "description": "Porcentaje del uso de la RAM",
     "gridPos": { "h": 4, "w": 3, "x": 3, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(1 - (node_memory_MemAvailable_bytes{instance=~\"$instance\"} / node_memory_MemTotal_bytes{instance=~\"$instance\"})) * 100"
      }
     ]
    },
    {
     "title": "Disk Used",
     "type": "gauge",
     "description": "Porcentaje del uso del Disco",
     "gridPos": { "h": 4, "w": 3, "x": 6, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(1 - (node_filesystem_avail_bytes{mountpoint=~\"$mountpoint\"} / node_filesystem_size_bytes{mountpoint=~\"$mountpoint\"})) * 100"
      }
     ]
    },
    {
     "title": "System Load",
     "type": "gauge",
     "description": "Porcentaje de procesos en cola para ejecutarse",
     "gridPos": { "h": 4, "w": 3, "x": 9, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "scalar(node_load1{instance=\"node-exporter:9100\", job=\"node\"}) * 100 / count(count(node_cpu_seconds_total{instance=\"node-exporter:9100\", job=\"node\"}) by (cpu))"
      }
     ]
    },
    {
     "title": "SWAP",
     "type": "gauge",
     "description": "Porcentaje uso de memoria en disco",
     "gridPos": { "h": 4, "w": 3, "x": 12, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(1 - (node_memory_SwapFree_bytes{instance=~\"$instance\"} / node_memory_SwapTotal_bytes{instance=~\"$instance\"})) * 100",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Disk Total Size",
     "type": "stat",
     "description": "Tamaño Total del Disco de la VM",
     "gridPos": { "h": 4, "w": 2, "x": 15, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "node_filesystem_size_bytes{fstype!=\"tmpfs\", mountpoint=\"/\"}"
      }
     ]
    },
    {
     "title": "CPU Cores",
     "type": "stat",
     "description": "Cantidad de Núcleos de CPU",
     "gridPos": { "h": 4, "w": 2, "x": 17, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count(node_cpu_seconds_total{mode=\"idle\"})"
      }
     ]
    },
    {
     "title": "RAM Total",
     "type": "stat",
     "description": "Memoria RAM Total",
     "gridPos": { "h": 4, "w": 2, "x": 19, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "node_memory_MemTotal_bytes" }
     ]
    },
    {
     "title": "UP Time",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 21, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "node_time_seconds - node_boot_time_seconds"
      }
     ]
    }
   ]
  },
  {
   "title": "CPU / RAM / DISK / NET BASIC",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Basic",
     "type": "timeseries",
     "description": "Uso del CPU por tipo",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "avg by (mode) (rate(node_cpu_seconds_total{instance=\"$instance\", job=\"$job\"}[1m])) * 100",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "RAM Basic",
     "type": "timeseries",
     "description": "Uso de la memoria RAM",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "node_memory_MemTotal_bytes{instance=\"$instance\", job=\"$job\"}",
       "legendFormat": "Total"
      },
      {
       "expr": "node_memory_MemFree_bytes{instance=\"$instance\", job=\"$job\"}",
       "legendFormat": "Free"
      },
      {
       "expr": "(node_memory_MemTotal_bytes{instance=\"$instance\", job=\"$job\"} - node_memory_MemAvailable_bytes{instance=\"$instance\", job=\"$job\"}) ",
       "legendFormat": "Used"
      },
      {
       "expr": "node_memory_Cached_bytes{instance=\"$instance\",job=\"$job\"} + node_memory_Buffers_bytes{instance=\"$instance\",job=\"$job\"} + node_memory_SReclaimable_bytes{instance=\"$instance\",job=\"$job\"}",
       "legendFormat": "Cache + Buffer"
      },
      {
       "expr": "(node_memory_SwapTotal_bytes{instance=\"$instance\",job=\"$job\"} - node_memory_SwapFree_bytes{instance=\"$instance\",job=\"$job\"})",
       "legendFormat": "Swap"
      }
     ]
    },
    {
     "title": "Disk Basic",
     "type": "timeseries",
     "description": "Uso del Disco",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "(1 - (node_filesystem_avail_bytes{fstype!=\"tmpfs\",instance=\"$instance\",job=\"$job\",mountpoint=\"/\"} / node_filesystem_size_bytes{fstype!=\"tmpfs\",instance=\"$instance\",job=\"$job\",mountpoint=\"/\"})) * 100",
       "legendFormat": "{{mountpoint}}"
      }
     ]
    },
    {
     "title": "Network ",
     "type": "timeseries",
     "description": "Tráfico de Entrada y de Salida en bytes por segundo",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "rate(node_network_receive_bytes_total{instance=\"$instance\",job=\"$job\"}[$__rate_interval])*8",
       "legendFormat": "Rx {{device}}"
      },
      {
       "expr": "rate(node_network_transmit_bytes_total{instance=\"$instance\",job=\"$job\"}[$__rate_interval])*8",
       "legendFormat": "Tx {{device}}"
      }
     ]
    }
   ]
  },
  {
   "title": "CPU DETAIL",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Used Core",
     "type": "timeseries",
     "description": "Uso del CPU por núcleo",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "100 - (rate(node_cpu_seconds_total{mode=\"idle\", instance=\"$instance\", job=\"$job\"}[1m]) * 100)",
       "legendFormat": "CPU Core {{cpu}}"
      }
     ]
    },
    {
     "title": "Load Average",
     "type": "timeseries",
     "description": "Promedio de procesos en cola para ejecutarse\n",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "node_load1{instance=\"$instance\", job=\"$job\"}",
       "legendFormat": "load1"
      },
      {
       "expr": "node_load5{instance=\"$instance\", job=\"$job\"}",
       "legendFormat": "load5"
      },
      {
       "expr": "node_load15{instance=\"$instance\", job=\"$job\"}",
       "legendFormat": "load15"
      }
     ]
    },
    {
     "title": "Procesos",
     "type": "timeseries",
     "description": "Cantidad de procesos ejecutándose y bloqueados",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "node_procs_running{instance=\"$instance\", job=\"$job\"}",
       "legendFormat": "Running"
      },
      {
       "expr": "node_procs_blocked{instance=\"$instance\", job=\"$job\"}",
       "legendFormat": "Blocked"
      }
     ]
    },
    {
     "title": "Interrupt",
     "type": "timeseries",
     "description": "Operaciones de Hardware por segundo",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "irate(node_intr_total{instance=\"$instance\",job=\"$job\"}[$__rate_interval])",
       "legendFormat": "Hardware"
      }
     ]
    }
   ]
  },
  {
   "title": "DISK DETAIL",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Disk Size",
     "type": "timeseries",
     "description": "Tamaño del Disco\n",
     "gridPos": { "h": 9, "w": 11, "x": 0, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "node_filesystem_size_bytes{fstype!=\"tmpfs\", instance=\"$instance\", job=\"$job\", mountpoint=~\"$mountpoint\"}",
       "legendFormat": "Total"
      },
      {
       "expr": "node_filesystem_size_bytes{fstype!=\"tmpfs\", instance=\"$instance\", job=\"$job\", mountpoint=~\"$mountpoint\"} - node_filesystem_avail_bytes{fstype!=\"tmpfs\", instance=\"$instance\", job=\"$job\", mountpoint=~\"$mountpoint\"}",
       "legendFormat": "Used"
      },
      {
       "expr": "node_filesystem_avail_bytes{fstype!=\"tmpfs\", instance=\"$instance\", job=\"$job\", mountpoint=~\"$mountpoint\"}",
       "legendFormat": "Free"
      }
     ]
    },
    {
     "title": "Disk Size Use",
     "type": "timeseries",
     "description": "Tamaño del Disco\n",
     "gridPos": { "h": 9, "w": 11, "x": 11, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "(node_filesystem_size_bytes{fstype!=\"tmpfs\",instance=\"$instance\",job=\"$job\",mountpoint=~\"$mountpoint\"} - node_filesystem_avail_bytes{fstype!=\"tmpfs\",instance=\"$instance\",job=\"$job\",mountpoint=~\"$mountpoint\"}) ",
       "legendFormat": "{{mountpoint}}"
      }
     ]
    },
    {
     "title": "Disk I/O Wait",
     "type": "gauge",
     "description": "Tiempo que espera el CPU esperando las operaciones del disco",
     "gridPos": { "h": 9, "w": 2, "x": 22, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg by (instance) (rate(node_cpu_seconds_total{mode=\"iowait\",instance=\"$instance\",job=\"$job\"}[1m])) * 100",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Disk I/O ops",
     "type": "timeseries",
     "description": "Cantidad de I/O por segundo\n\n",
     "gridPos": { "h": 11, "w": 8, "x": 0, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "rate(node_disk_reads_completed_total{instance=\"$instance\",job=\"$job\"}[1m])",
       "legendFormat": "Read {{device}}"
      },
      {
       "expr": "rate(node_disk_writes_completed_total{instance=\"$instance\",job=\"$job\"}[1m])",
       "legendFormat": "Write {{device}}"
      }
     ]
    },
    {
     "title": "Disk Throughput",
     "type": "timeseries",
     "description": "Cantidad de MB/s de I/O en el disco\n\n",
     "gridPos": { "h": 11, "w": 8, "x": 8, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "rate(node_disk_read_bytes_total{instance=\"$instance\",job=\"$job\"}[1m])",
       "legendFormat": "Read {{device}}"
      },
      {
       "expr": "rate(node_disk_written_bytes_total{instance=\"$instance\",job=\"$job\"}[1m])",
       "legendFormat": "Write {{device}}"
      }
     ]
    },
    {
     "title": "Inodes",
     "type": "timeseries",
     "description": "Porcentaje de Inodos en uso",
     "gridPos": { "h": 11, "w": 8, "x": 16, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "(1 - (node_filesystem_files_free{fstype!=\"tmpfs\",instance=\"$instance\",job=\"$job\",mountpoint=~\"$mountpoint\"} / node_filesystem_files{fstype!=\"tmpfs\",instance=\"$instance\",job=\"$job\",mountpoint=~\"$mountpoint\"})) * 100",
       "legendFormat": "{{mountpoint}}"
      }
     ]
    }
   ]
  },
  {
   "title": "NETWORK DETAIL",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total Use",
     "type": "gauge",
     "description": "Porcentaje tráfico actual (Rx+Tx)",
     "gridPos": { "h": 6, "w": 4, "x": 0, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "Mbits" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(rate(node_network_receive_bytes_total{device=\"$device\"}[1m]) + rate(node_network_transmit_bytes_total{device=\"$device\"}[1m])) * 8 / 1000000",
       "legendFormat": "{{device}}"
      }
     ]
    },
    {
     "title": "Throughput",
     "type": "timeseries",
     "description": "Velocidad de tráfico de entrada y salida por segundo",
     "gridPos": { "h": 6, "w": 10, "x": 4, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "Mbits" } },
     "targets": [
      {
       "expr": "rate(node_network_receive_bytes_total{device=\"$device\"}[1m])",
       "legendFormat": "Rx {{device}}"
      },
      {
       "expr": "rate(node_network_transmit_bytes_total{device=\"$device\"}[1m])",
       "legendFormat": "Tx {{device}}"
      }
     ]
    },
    {
     "title": "Packet",
     "type": "timeseries",
     "description": "Cantidad de paquetes recibidos y enviados por segundo",
     "gridPos": { "h": 6, "w": 10, "x": 14, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "expr": "rate(node_network_receive_packets_total{device=\"$device\"}[1m])",
       "legendFormat": "Rx {{device}}"
      },
      {
       "expr": "rate(node_network_transmit_packets_total{device=\"$device\"}[1m])",
       "legendFormat": "Tx {{device}}"
      }
     ]
    },
    {
     "title": "TCP Conections",
     "type": "stat",
     "description": "Número de conexiones TCP establecidas",
     "gridPos": { "h": 6, "w": 3, "x": 0, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "node_netstat_Tcp_CurrEstab{instance=\"$instance\",job=\"$job\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Error",
     "type": "stat",
     "description": "Errores de recepción y transmisión por segundo",
     "gridPos": { "h": 6, "w": 7, "x": 3, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "rate(node_network_receive_errs_total{device=\"$device\"}[1m])",
       "legendFormat": "Rx {{device}}"
      },
      {
       "expr": "rate(node_network_transmit_errs_total{device=\"$device\"}[1m])",
       "legendFormat": "Tx {{device}}"
      }
     ]
    },
    {
     "title": "Drops",
     "type": "stat",
     "description": "Paquetes descartados por segundo",
     "gridPos": { "h": 6, "w": 7, "x": 10, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "rate(node_network_receive_drop_total{device=\"$device\"}[1m])",
       "legendFormat": "Rx {{device}}"
      },
      {
       "expr": "rate(node_network_transmit_drop_total{device=\"$device\"}[1m])",
       "legendFormat": "Tx {{device}}"
      }
     ]
    },
    {
     "title": "Syncookies",
     "type": "stat",
     "description": "Actividad de Syncookies por segundo (seguridad/saturación de sockets)",
     "gridPos": { "h": 6, "w": 7, "x": 17, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "eps" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "rate(node_netstat_TcpExt_SyncookiesRecv{instance=\"$instance\",job=\"$job\"}[1m])",
       "legendFormat": "Recv"
      },
      {
       "expr": "rate(node_netstat_TcpExt_SyncookiesSent{instance=\"$instance\",job=\"$job\"}[1m])",
       "legendFormat": "Sent"
      }
     ]
    }
   ]
  }
 ]
}