{
 "title": "Monitoreo Postgres",
 "tags": [ "POSTGRES" ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(node_cpu_seconds_total,instance)"
    }
   },
   { "name": "job", "label": "Job", "query": { "query": "label_values(up,job)" } },
   {
    "name": "container",
    "label": "Container",
    "query": {
     "query": "label_values(container_cpu_usage_seconds_total,name)"
    }
   },
   {
    "name": "datname",
    "label": "DatName",
    "query": {
     "query": "label_values(pg_stat_activity_count,datname)"
    }
   },
   {
    "name": "mountpoint",
    "label": "MountPoint",
    "query": {
     "query": "label_values(node_filesystem_size_bytes,mountpoint)"
    }
   },
   {
    "name": "device",
    "label": "Device",
    "query": {
     "query": "label_values(node_network_receive_bytes_total,device)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "OVERVIEW",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Conexiones Abiertas",
     "type": "stat",
     "description": "Total de conexiones abiertas",
     "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(pg_stat_activity_count{datname=\"$datname\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Conexiones Activas",
     "type": "stat",
     "description": "Conexiones que están ejecutando queries",
     "gridPos": { "h": 4, "w": 3, "x": 3, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(pg_stat_activity_count{datname=\"$datname\", state=\"active\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "TPS",
     "type": "gauge",
     "description": "Cantidad de transacciones (Commit + Rollback) por segundo",
     "gridPos": { "h": 4, "w": 3, "x": 6, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "rate(pg_stat_database_xact_commit{datname=~\"$datname\"}[1m]) + rate(pg_stat_database_xact_rollback{datname=~\"$datname\"}[1m])",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Commit",
     "type": "gauge",
     "description": "Transacciones exitosas por segundo",
     "gridPos": { "h": 4, "w": 3, "x": 9, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "rate(pg_stat_database_xact_commit{datname=~\"$datname\"}[1m])",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Rollback",
     "type": "gauge",
     "description": "Transacciones abortadas por segundo",
     "gridPos": { "h": 4, "w": 3, "x": 12, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "rate(pg_stat_database_xact_rollback{datname=~\"$datname\"}[1m])",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Lock",
     "type": "stat",
     "description": "Cantidad de bloqueos activos",
     "gridPos": { "h": 4, "w": 3, "x": 15, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(pg_locks_count{datname=~\"$datname\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Cache Hit",
     "type": "gauge",
     "description": "Porcentaje de lecturas servidas desde cache vs disco",
     "gridPos": { "h": 4, "w": 3, "x": 18, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(rate(pg_stat_database_blks_hit{datname=~\"$datname\"}[5m]) / (rate(pg_stat_database_blks_hit{datname=~\"$datname\"}[5m]) + rate(pg_stat_database_blks_read{datname=~\"$datname\"}[5m]))) * 100",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Index Usage Ratio",
     "type": "stat",
     "description": "Porcentaje de consultas que usan índices vs. secuenciales",
     "gridPos": { "h": 2, "w": 3, "x": 21, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(sum(rate(pg_stat_user_tables_idx_scan{datname=\"$datname\"}[5m])) / (sum(rate(pg_stat_user_tables_idx_scan{datname=\"$datname\"}[5m])) + sum(rate(pg_stat_user_tables_seq_scan{datname=\"$datname\"}[5m])))) * 100",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Vacuum",
     "type": "stat",
     "description": "Limpieza de filas muertas",
     "gridPos": { "h": 2, "w": 3, "x": 21, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(pg_stat_activity_count{datname=\"$datname\", state=\"active\", query=~\".*VACUUM.*\"})",
       "legendFormat": "{{datname}}"
      }
     ]
    }
   ]
  },
  {
   "title": "DML",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Insert Operations",
     "type": "timeseries",
     "description": "Cantidad de registros insertados por segundo",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "rate(pg_stat_database_tup_inserted{datname=\"$datname\"}[1m])",
       "legendFormat": "{{datname}}"
      }
     ]
    },
    {
     "title": "Update Operations",
     "type": "timeseries",
     "description": "Cantidad de registros actualizado por segundo",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(pg_stat_database_tup_updated{datname=\"$datname\"}[1m])",
       "legendFormat": "{{datname}}"
      }
     ]
    },
    {
     "title": "Delete Operations",
     "type": "timeseries",
     "description": "Cantidad de registros borrados por segundo",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(pg_stat_database_tup_updated{datname=\"$datname\"}[1m])",
       "legendFormat": "{{datname}}"
      }
     ]
    }
   ]
  },
  {
   "title": "TPS",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Commit",
     "type": "timeseries",
     "description": "Cantidad de transacciones confirmadas (Commit) por segundo",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "rate(pg_stat_database_xact_commit{datname=\"$datname\"}[1m])",
       "legendFormat": "{{datname}}"
      }
     ]
    },
    {
     "title": "Rollback",
     "type": "timeseries",
     "description": "Cantidad de transacciones abortadas (Rollback) por segundo",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "rate(pg_stat_database_xact_rollback{datname=\"$datname\"}[1m])",
       "legendFormat": "{{datname}}"
      }
     ]
    }
   ]
  },
  {
   "title": "LOCKS",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Lock",
     "type": "timeseries",
     "description": "Cantidad de bloqueos",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "pg_locks_count{datname=\"$datname\"}",
       "legendFormat": "{{datname}},{{mode}}"
      }
     ]
    },
    {
     "title": "DeadLock",
     "type": "timeseries",
     "description": "Cantidad de bloqueos mutuos detectados por segundo",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "eps" } },
     "targets": [
      {
       "expr": "rate(pg_stat_database_deadlocks{datname=~\"$datname\"}[1m])",
       "legendFormat": "{{datname}}"
      }
     ]
    }
   ]
  },
  {
   "title": "MAINTENANCE",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "Tuples",
     "type": "timeseries",
     "description": "Diferencia entre filas leídas desde el disco y filas devueltas a la aplicación",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "rate(pg_stat_database_tup_fetched{datname=\"$datname\"}[1m])",
       "legendFormat": "Row Fetched"
      },
      {
       "expr": "rate(pg_stat_database_tup_returned{datname=\"$datname\"}[1m])",
       "legendFormat": "Row Returned"
      }
     ]
    },
    {
     "title": "Chekpoint",
     "type": "timeseries",
     "description": "Diferencia entre filas leídas y filas devueltas",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "eps" } },
     "targets": [
      {
       "expr": "rate(pg_stat_bgwriter_checkpoints_timed_total[5m])",
       "legendFormat": "Timed"
      },
      {
       "expr": "rate(pg_stat_bgwriter_checkpoints_req_total[5m])",
       "legendFormat": "Requested"
      }
     ]
    }
   ]
  }
 ]
}