{
 "title": "Overview",
 "description": "Monitoreo simple y global de la aplicación",
 "tags": [
  "VPS",
  "DOCKER",
  "NGINX",
  "POSTGRES"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(node_cpu_seconds_total,instance)"
    }
   },
   { "name": "job", "label": "Job", "query": { "query": "label_values(up,job)" } },
   {
    "name": "container",
    "label": "Container",
    "query": {
     "query": "label_values(container_cpu_usage_seconds_total,name)"
    }
   },
   {
    "name": "datname",
    "label": "DatName",
    "query": {
     "query": "label_values(pg_stat_activity_count,datname)"
    }
   },
   {
    "name": "mountpoint",
    "label": "MountPoint",
    "query": {
     "query": "label_values(node_filesystem_size_bytes,mountpoint)"
    }
   }
  ]
 },
 "panels": [
  { "title": "VPS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU Used",
   "type": "gauge",
   "description": "Porcentaje del uso del CPU",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (avg by (instance)(rate(node_cpu_seconds_total{mode=\"idle\", instance=~\"$instance\"}[1m])) * 100)"
    }
   ]
  },
  {
   "title": "RAM Used",
   "type": "gauge",
   "description": "Porcentaje del uso de la RAM",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(1 - (node_memory_MemAvailable_bytes{instance=~\"$instance\"} / node_memory_MemTotal_bytes{instance=~\"$instance\"})) * 100"
    }
   ]
  },
  {
   "title": "Disk Used",
   "type": "gauge",
   "description": "Porcentaje del uso del Disco",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(1 - (node_filesystem_avail_bytes{mountpoint=~\"$mountpoint\"} / node_filesystem_size_bytes{mountpoint=~\"$mountpoint\"})) * 100"
    }
   ]
  },
  {
   "title": "System Load",
   "type": "gauge",
   "description": "Porcentaje de procesos en cola para ejecutarse",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "scalar(node_load1{instance=\"node-exporter:9100\", job=\"node\"}) * 100 / count(count(node_cpu_seconds_total{instance=\"node-exporter:9100\", job=\"node\"}) by (cpu))"
    }
   ]
  },
  {
   "title": "SWAP",
   "type": "gauge",
   "description": "Porcentaje uso de memoria en disco",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(1 - (node_memory_SwapFree_bytes{instance=~\"$instance\"} / node_memory_SwapTotal_bytes{instance=~\"$instance\"})) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk Total Size",
   "type": "stat",
   "description": "Tamaño Total del Disco de la VM",
   "gridPos": { "h": 4, "w": 2, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{fstype!=\"tmpfs\", mountpoint=\"/\"}"
    }
   ]
  },
  {
   "title": "CPU Cores",
   "type": "stat",
   "description": "Cantidad de Núcleos de CPU",
   "gridPos": { "h": 4, "w": 2, "x": 17, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(node_cpu_seconds_total{mode=\"idle\"})"
    }
   ]
  },
  {
   "title": "RAM Total",
   "type": "stat",
   "description": "Memoria RAM Total",
   "gridPos": { "h": 4, "w": 2, "x": 19, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "node_memory_MemTotal_bytes" }
   ]
  },
  {
   "title": "UP Time",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_time_seconds - node_boot_time_seconds"
    }
   ]
  },
  { "title": "POSTGRES", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Conexiones Abiertas",
   "type": "stat",
   "description": "Total de conexiones abiertas",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(pg_stat_activity_count{datname=~\"$datname\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Conexiones Activas",
   "type": "stat",
   "description": "Conexiones que están ejecutando queries",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(pg_stat_activity_count{datname=~\"$datname\", state=\"active\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "TPS",
   "type": "gauge",
   "description": "Cantidad de transacciones (Commit + Rollback) por segundo",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(pg_stat_database_xact_commit{datname=~\"$datname\"}[1m]) + rate(pg_stat_database_xact_rollback{datname=~\"$datname\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Commit",
   "type": "gauge",
   "description": "Transacciones exitosas por segundo",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(pg_stat_database_xact_commit{datname=~\"$datname\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rollback",
   "type": "gauge",
   "description": "Transacciones abortadas por segundo",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(pg_stat_database_xact_rollback{datname=~\"$datname\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Lock",
   "type": "stat",
   "description": "Cantidad de bloqueos activos",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(pg_locks_count{datname=~\"$datname\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cache Hit",
   "type": "gauge",
   "description": "Porcentaje de lecturas servidas desde cache vs disco",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(rate(pg_stat_database_blks_hit{datname=~\"$datname\"}[5m]) / (rate(pg_stat_database_blks_hit{datname=~\"$datname\"}[5m]) + rate(pg_stat_database_blks_read{datname=~\"$datname\"}[5m]))) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Index Usage Ratio",
   "type": "stat",
   "description": "Porcentaje de consultas que usan índices vs. secuenciales",
   "gridPos": { "h": 2, "w": 3, "x": 21, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(rate(pg_stat_user_tables_idx_scan{datname=\"$datname\"}[5m])) / (sum(rate(pg_stat_user_tables_idx_scan{datname=\"$datname\"}[5m])) + sum(rate(pg_stat_user_tables_seq_scan{datname=\"$datname\"}[5m])))) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Vacuum",
   "type": "stat",
   "description": "Limpieza de filas muertas",
   "gridPos": { "h": 2, "w": 3, "x": 21, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(pg_stat_activity_count{datname=\"$datname\", state=\"active\", query=~\".*VACUUM.*\"})",
     "legendFormat": "{{datname}}"
    }
   ]
  },
  { "title": "DOCKER", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "CPU Use",
   "type": "gauge",
   "description": "Porcentaje de uso de CPU de todos los contenedores",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_user_seconds_total{image!=\"\"}[5m]) * 100)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "RAM Use",
   "type": "stat",
   "description": "Porcentaje de uso de RAM de todos los contenedores",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{image!=\"\"})",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Cache Size",
   "type": "stat",
   "description": "Tamaño del Cache",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "docker_cache_size_total", "legendFormat": "{{name}}" }
   ]
  },
  {
   "title": "Total Containers",
   "type": "stat",
   "description": "Cantidad total de contenedores",
   "gridPos": { "h": 2, "w": 3, "x": 9, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "docker_containers_total" }
   ]
  },
  {
   "title": "Running Containers",
   "type": "stat",
   "description": "Cantidad de contenedores en ejecución",
   "gridPos": { "h": 2, "w": 3, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "docker_containers_active" }
   ]
  },
  {
   "title": "Total Images",
   "type": "stat",
   "description": "Cantidad total de imágenes",
   "gridPos": { "h": 2, "w": 3, "x": 15, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "docker_images_total" }
   ]
  },
  {
   "title": "Actives Images",
   "type": "stat",
   "description": "Cantidad de imágenes asociadas con contenedores activos",
   "gridPos": { "h": 2, "w": 3, "x": 18, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "docker_images_active" }
   ]
  },
  {
   "title": "Inactve Images",
   "type": "stat",
   "description": "Cantidad de imágenes no asociadas a contenedores activos",
   "gridPos": { "h": 2, "w": 3, "x": 21, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "docker_images_inactive" }
   ]
  },
  {
   "title": "Active Size Containers",
   "type": "stat",
   "description": "Tamaño total de los contenedores activos",
   "gridPos": { "h": 2, "w": 3, "x": 9, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(container_fs_usage_bytes{name!=\"\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Exited Containers",
   "type": "stat",
   "description": "Cantidad de contenedores en parados",
   "gridPos": { "h": 2, "w": 3, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "docker_containers_exited" }
   ]
  },
  {
   "title": "Total Size Images",
   "type": "stat",
   "description": "Tamaño total de las imágenes",
   "gridPos": { "h": 2, "w": 3, "x": 15, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(docker_image_size_active{name!=\"\"}) + sum(docker_image_size_inactive{name!=\"\"} or vector(0))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Active Size Images",
   "type": "stat",
   "description": "Tamaño total de las imágenes activas",
   "gridPos": { "h": 2, "w": 3, "x": 18, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(docker_image_size_active{name!=\"\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Inactive Size Images",
   "type": "stat",
   "description": "Tamaño total de las imágenes no asociadas a un contenedor activo",
   "gridPos": { "h": 2, "w": 3, "x": 21, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(docker_image_size_inactive{name!=\"\"})",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}